logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

spring:
#  datasource:
#    url: jdbc:h2:mem:h2-demo
#    username: sa
#    password: 
#    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  h2:
    console:
      enabled: true